# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df5265f4b0d0461a7c33bd311090d4e1b437a7635c61968e2e458542f63e4320fcf831620b3a418ce48886fbd88b39468b8c8991b553cd271aa5dedc83cd4e7d

test:
  secret_key_base: 7d7a574e279857dd2143ff33f6dfb23a4db55b43aed6e91901530fea31ac0df87cdd2c6e0b730844552977d388ba47520a22b52ecd96f8581b495428c3d0efc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
